### PR TITLE
Update Resources

### PR DESCRIPTION
**Pull request by ChaseC99**
- Add description page for sponsor resources
- Update the json file to include resources from sponsors and mentors
- Add "Resources" to the navbar

### CODE REVIEW

**Comment by nathan-tang** [comment]
i can fix merge conflict ty!

**Comment by nathan-tang** [comment]
sike that works too thank you LMAO

**Comment by ChaseC99** [comment]
> i can fix merge conflict ty!

oops sorry I just did! You're quick with the review 👀

**Comment by nathan-tang** [comment]
> > i can fix merge conflict ty!
> 
> oops sorry I just did! You're quick with the review 👀

have github open been doing last minute prepping for tomorrow LMAO, did you still want to add that /feedback route btw?

**Pull request merged**
